# Generated by Django 5.1.6 on 2025-07-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('return_requested', 'Return Requested'), ('returned', 'Returned'), ('refund_rejected', 'Refund Rejected')], default='pending', max_length=20),
        ),
    ]
