# Generated by Django 5.1.6 on 2025-07-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_image',
            field=models.ImageField(blank=True, null=True, upload_to='returns/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_reason',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_status',
            field=models.CharField(choices=[('none', 'No Return'), ('requested', 'Return Requested'), ('approved', 'Return Approved'), ('rejected', 'Return Rejected'), ('completed', 'Return Completed')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_type',
            field=models.CharField(blank=True, choices=[('refund', 'Refund'), ('exchange', 'Exchange')], max_length=20, null=True),
        ),
    ]
