# Generated by Django 5.1.6 on 2025-08-01 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderitem_shipment_id_orderitem_shipment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shipment_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='shipment_status',
        ),
    ]
