# Generated by Django 5.1.6 on 2025-08-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_orderitem_shipment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('return_requested', 'Return Requested'), ('returned', 'Returned'), ('refund_rejected', 'Refund Rejected')], default='pending', max_length=20),
        ),
    ]
